name: Daily Auto Commit

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 4:00 AM UTC

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "24f1001631@ds.study.iitm.ac.in"

      - name: Make a change
        run: echo "Last run: $(date)" > last-run.txt

      - name: Commit and push changes
        run: |
          git add last-run.txt
          git commit -m "Automated commit on $(date)"
          git push
